# Generated by Django 5.1.1 on 2024-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('predicted_outcome', models.CharField(blank=True, max_length=10)),
                ('team_a_win_probability', models.FloatField(blank=True, null=True)),
                ('team_b_win_probability', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
